

FILE(MAKE_DIRECTORY ${BUILDDIR})
FILE(REMOVE_RECURSE ${BUILDDIR}/ROpenFLUID)
FILE(MAKE_DIRECTORY ${BUILDDIR}/ROpenFLUID)

FILE(COPY "${PACKAGESRCDIR}/" 
       DESTINATION "${PACKAGEBUILDDIR}"
       PATTERN ".*" EXCLUDE
       PATTERN "_*" EXCLUDE
       PATTERN "*.cmake" EXCLUDE)


CONFIGURE_FILE(${RESOURCESDIR}/DESCRIPTION.in ${PACKAGEBUILDDIR}/DESCRIPTION @ONLY)

CONFIGURE_FILE(${RESOURCESDIR}/man/ROpenFLUID-package.Rd.in ${PACKAGEBUILDDIR}/man/ROpenFLUID-package.Rd @ONLY)
CONFIGURE_FILE(${RESOURCESDIR}/tests/00tests.R.in ${PACKAGEBUILDDIR}/tests/00tests.R @ONLY)
CONFIGURE_FILE(${RESOURCESDIR}/tests/PrimitivesExample.R.in ${PACKAGEBUILDDIR}/tests/PrimitivesExample.R @ONLY)


EXECUTE_PROCESS(COMMAND "${CMAKE_COMMAND}" 
                "-E" "chdir" "${BUILDDIR}"
                "R" "CMD" "BATCH" "--vanilla" "${RESOURCESDIR}/roxygen2.R")
