

FILE(MAKE_DIRECTORY ${BUILDDIR})
FILE(REMOVE_RECURSE ${BUILDDIR}/ROpenFLUID)
FILE(MAKE_DIRECTORY ${BUILDDIR}/ROpenFLUID)

FILE(COPY "${PACKAGESRCDIR}/" 
       DESTINATION "${PACKAGEBUILDDIR}"
       PATTERN ".*" EXCLUDE
       PATTERN "_*" EXCLUDE
       PATTERN "*.cmake" EXCLUDE)


CONFIGURE_FILE(${RESOURCESDIR}/DESCRIPTION.in ${PACKAGEBUILDDIR}/DESCRIPTION @ONLY)
CONFIGURE_FILE(${RESOURCESDIR}/configure.ac.in ${PACKAGEBUILDDIR}/configure.ac @ONLY)

CONFIGURE_FILE(${RESOURCESDIR}/man/ROpenFLUID-package.Rd.in ${PACKAGEBUILDDIR}/man/ROpenFLUID-package.Rd @ONLY)


